included:
  - EtherealVeil

excluded:
  - EtherealVeil/EtherealVeilTests
  - EtherealVeil/EtherealVeilUITests

opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - identical_operands
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - trailing_whitespace  # handled by editor

line_length:
  warning: 130
  error: 160

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

identifier_name:
  min_length: 2
  excluded:
    - id
    - p

reporter: "xcode"
